- ckanext/showcase/templates/showcase/read.html
Implements #6.
It turns out you only need og:url and og:image, and showcases now get embedded properly.
See http://iframely.com/debug?uri=http%3A%2F%2Fdata.beta.nyc%2Fshowcase%2Fthe-children-of-vision-zero-2014
> Adds og:image and og:url Open Graph markup

- ckanext/showcase/plugin.py
I check the minimal version required (2.4) instead of using negative logic. (related to #20)
> Fix issue about add_ckan_admin_tab_plugin_notfound

- ckanext/showcase/templates/showcase/edit_base.html
- ckanext/showcase/templates/showcase/read.html
Fixes #31: Previously, it was tried to load CSS files from the server's root
directory. This fails if CKAN is running in a subdirectory.
With this change, the CSS file URLs are prefixed by CKAN's `site_url`
configuration setting.
> Fix #31: Take site_url into account when loading CSS.

- ckanext/showcase/logic/schema.py
Migrating relations to showcases failed with error 'Converter `ignore_missing` does not exist' because 'ignore-missing' is not a converter but a validator.
> change 'ignore_missing' to validator

- ckanext/showcase/templates/showcase/read.html
- ckanext/showcase/templates/showcase/snippets/showcase_info.html
The C-Var can not be used in a snippet. Therefore the attribute showcase_pkgs is included in the call of the snippet to provide the information of c.showcase_pkgs.
Otherwise an error occurs when trying to display the showcase-information-page.
> fix usage of context-var in snippet

- ckanext/showcase/tests/__init__.py
- ckanext/showcase/tests/action/test_create.py
- ckanext/showcase/tests/action/test_delete.py
- ckanext/showcase/tests/action/test_get.py
- ckanext/showcase/tests/test_auth.py
- ckanext/showcase/tests/test_converters.py
- ckanext/showcase/tests/test_helpers.py
- ckanext/showcase/tests/test_plugin.py
Showcase model tables aren't always created when the tests run, resulting in errors during test setup. This creates a new `ShowcaseFunctionalTestBase` that explicitly sets up the model tables for each test.
> Showcase models should be setup for tests

- README.rst
- ckanext/showcase/commands/migrate.py
I implemented the option to migrate relations to showcases when there are duplicate relations present.
You can append the 'force'-option to the original migrate command and it will create showcases as 
'duplicate_' + original_related_title + '_' + hash
That way you can resolve resulting issues as showcases, if you prefer it.
> integrate force option for migration of relations

- ckanext/showcase/logic/schema.py
In the *_show schema the convert_from_extras converter should be placed
first, as at this point the field does not yet exist and with
ignore_missing the whole process is cancelled. Only if the order is like
that, we actually get a new field image_url as intended.
This is described here as well: http://docs.ckan.org/en/latest/extensions/adding-custom-fields.html#updating-the-ckan-schema
With the current code, this leads to the unfortunate situation, that one can upload an image to a showcase, but it is not displayed because the `image_url` field is not generated correctly, which subsequently does not generate the `image_display_url` field.
> Use convert_from_extras before ignore_missing

- ckanext/showcase/templates/package/read_base.html
- ckanext/showcase/templates/showcase/read.html
The showcase read_base package template neglects to call `super()`. This is probably because we don't want the 'Related' tab on the dataset nav bar. However, it has the consequence of making the extension incompatible with any other extension that also wants to extend the nav bar.
I will open an issue on ckan itself to make the 'Related' tab optional based on a config setting. That seems to me the cleanest option.
> Header override

- ckanext/showcase/logic/action/get.py
This is a fix for #41 as the issue also occurs when the showcase list is accessed and one showcase has an association with a deleted package. In that case the showcase-list-view can not be displayed as a not authorized user (not logged in).
This prevents the said dataset from being added to the view when it can not be accessed by package_show.
> except NotAuthorized when package can not be viewed

- README.rst
This fixes the issue, similar to https://github.com/ckan/ckanext-showcase/issues/41
When accessing the list of showcases, that are related to a certain package:
When one of the showcases has a relation to a deleted dataset, an error occurs. This PR uses the same approach like https://github.com/ckan/ckanext-showcase/pull/45 that already got merged.
> Except NotAuthorized on Showcase-List

- ckanext/showcase/templates/showcase/edit_base.html
- ckanext/showcase/templates/showcase/read.html
- ckanext/showcase/templates/showcase/snippets/showcase_item.html
I noticed some small template issues: some images were not responsive, and the main column on the edit-showcase page was narrow and floating right. This PR fixes those.
> Fix templates

- ckanext/showcase/templates/package/dataset_showcase_list.html
The button on the dataset page that adds showcases to a dataset is confusingly named 'Add to showcase' while it should be named the opposite.
> change button-text to the action it is doing

- ckanext/showcase/logic/helpers.py
The statistics-snippet on the homepage displays the number of showcases on the portal.
The number seems to be the addition number of datasets + number of showcases. 
This fixes the query and displays the correct number for all entities.
> fix query to display correct number of showcases

- MANIFEST.in
We need to include webassets.yml in the `MANIFEST.in` or it would not be included in the source install causing CKAN to not found the assets:
```
2021-03-31 17:29:54,687 ERROR [ckan.lib.webassets_tools] [Dummy-82] Trying to include unknown asset: <showcase/ckanext-showcase-css>
2021-03-31 17:29:54,782 ERROR [ckan.lib.webassets_tools] [Dummy-82] Trying to include unknown asset: <showcase/ckeditor>
```
Currently if we execute an install using something like:
```
pip install git+https://github.com/ckan/ckanext-showcase.git@v1.4.0#egg=ckanext-showcase
```
The resulting folder doesn't contain the `webasset.yml` file:
```
~$ ls /usr/local/lib/python2.7/dist-packages/ckanext/showcase/fanstatic/
ckanext_showcase.css  ckeditor-content-style.css  dist  js  src
```
> Include webassets.yml in MANIFEST.in

- ckanext/showcase/templates/showcase/snippets/showcase_search_form.html
Currently CKAN core has a `<h1>` tag to wrap-up the search result text: https://github.com/ckan/ckan/blob/3c4ae58969058b8c0a335a960010855ded5f3640/ckan/templates/snippets/search_form.html#L50
Using h1 instead of h2 will make CSS styling easier across extensions.
> Search Results Style: Use same tag than core

- ckanext/showcase/templates/showcase/confirm_delete.html
- ckanext/showcase/utils.py
The manage datasets route name was hardcoded to the PRE-2.9 name
The delete showcase route name was hardcoded to the PRE-2.9 name
> The manage datasets route name was hardcoded

- ckanext/showcase/logic/action/get.py
the solr logic for more that one showcase ids should be
fq=id:(id1 OR id2 ...) instead of fq=id:id1 OR id2
> repair logic 'showcase_package_list'

- ckanext/showcase/logic/action/get.py
the solr logic for more that one package ids should be
fq=id:(id1 OR id2 ...) instead of fq=id:id1 OR id2
> repair logic 'package_showcase_list'

- README.rst
RST interprets a word with a trailing underscore as a link, and compilation fails with 'Unknown target name' if it is not one.
> Escape trailing underscore

- ckanext/showcase/templates/admin/confirm_remove_showcase_admin.html
- ckanext/showcase/templates/admin/manage_showcase_admins.html
- ckanext/showcase/templates/package/dataset_showcase_list.html
- ckanext/showcase/templates/package/read_base.html
- ckanext/showcase/templates/showcase/add_datasets.html
- ckanext/showcase/templates/showcase/confirm_delete.html
- ckanext/showcase/templates/showcase/manage_datasets.html
- ckanext/showcase/templates/showcase/snippets/showcase_item.html
Fixes:
- Adds csrf_input() to all forms
- Fix BS5 `btn-sm` class.
> Fixes BS5 class and add CSRF support to all forms

- .github/workflows/test.yml
- MANIFEST.in
- setup.py
If possible, please release a new tag/version
Test for CKAN 2.9 started failing due to a setptools conflicts
After fixing that, a solr9 schema error appears
The tests were divided into two files
A new approach with lates version only compatible with latest CKAN and older version branches here compatible with older CKAN version will dramatically reduce times for PRs here.
It's always possible to backport new features for older version branches
> Update MANIFEST.in to include migration files and public assets

- ckanext/showcase/templates/showcase/new_package_form.html
Currently, `c.form_action` and `c.form_style` do not return anything.
This means that the logic for displaying the `delete` and `update` buttons will not work.
Refactored code to avoid using `c.` to assign `action` and `form_style` variables.
> Fixes delete and update showcase buttons

- ckanext/showcase/templates/admin/confirm_remove_showcase_admin.html
- ckanext/showcase/templates/admin/manage_showcase_admins.html
- ckanext/showcase/templates/package/dataset_showcase_list.html
- ckanext/showcase/templates/showcase/add_datasets.html
- ckanext/showcase/templates/showcase/confirm_delete.html
- ckanext/showcase/templates/showcase/edit_base.html
- ckanext/showcase/templates/showcase/manage_datasets.html
- ckanext/showcase/templates/showcase/read.html
- ckanext/showcase/templates/showcase/search.html
- ckanext/showcase/utils.py
- ckanext/showcase/views.py
This PR was initially just to pass in the `search_facets` parameter into the `facet_list.html` template, as it's now required. Then I got the idea of cleaning up the old `c` object from the templates too.
@pdelboca Do I have it right that we should be passing these extra variables along as `extra_vars` and *not* adding them to the `g` object, in the views? I didn't change that yet, but I can also clean up the places where we add to the `g` object there as well.
> Clean up c object

- ckanext/showcase/plugin.py
- ckanext/showcase/tests/test_plugin.py
If we have the following four showcases and sort the showcase index page by 'Name Ascending', we ought to see:
- anna's Showcase
- Bob's Showcase
- Ömer's Showcase
- "Petra"'s Showcase
With the current state of the code, we would see:
- "Petra"'s Showcase
- Bob's Showcase
- anna's Showcase
- Ömer's Showcase
> Munge title strings for better sorting
